2020-06-28 00:00:28,408 ERROR: Exception on /auth/reset_password_request [POST] [in c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\auth\email.py", line 11, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token = token, _external = True)}}
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-06-28 00:05:29,803 INFO: Microblog startup [in C:\Users\DELL E7240\Desktop\microblog.2\app\__init__.py:74]
2020-06-28 00:06:31,726 ERROR: Exception on /auth/reset_password_request [POST] [in c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\auth\email.py", line 11, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token = token, _external = True)}}
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-06-28 00:07:47,710 INFO: Microblog startup [in C:\Users\DELL E7240\Desktop\microblog.2\app\__init__.py:74]
2020-06-28 00:07:58,446 ERROR: Exception on /auth/reset_password_request [POST] [in c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\auth\email.py", line 13, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\DELL E7240\Desktop\microblog.2\app\templates\email\reset_password.html", line 6, in top-level template code
    <p>{{url_for('reset_password', token = token, _external = True)}}</p>
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\dell e7240\desktop\microblog.2\env\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
